image: docker:19.03.5

services:
  - docker:19.03.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_PREFIX: "quay.io/andrleite/"

stages:
  - build
  - deploy

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - eval $(ssh-agent -s)
  - echo "${GIT_SSH_PRIV_KEY}" | ssh-add -
  - apk add git
  - git config --global user.email "${GITHUB_USER_EMAIL}"
  - git config --global user.name "${GITHUB_USER}"
  - mkdir -p ~/.ssh

build:
  stage: build
  script:
    - docker build --build-arg COLOR=${CI_COMMIT_REF_NAME} -t ${IMAGE_PREFIX}rollouts-demo:${CI_COMMIT_REF_NAME} .
    - docker push ${IMAGE_PREFIX}rollouts-demo:${CI_COMMIT_REF_NAME}

deploy:
  stage: deploy
  before_script:
    - |
        curl -s -0 -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.3/kustomize_v3.5.3_linux_amd64.tar.gz  \
        | tar -C /usr/local/bin -xzf -
  script:
    - TMP_DIR=$(mktemp -d)
    - cd ${TMP_DIR}
    - git clone git@github.com:andrleite/argo-apps.git
    - cd argo-apps/${CI_PROJECT_NAME}
    - cp -a kustomize/ ${TMP_DIR}
    - ( cd ${TMP_DIR} && \
      kustomize edit set image quay.io/andrleite/rollouts-demo=quay.io/andrleite/rollouts-demo:${CI_COMMIT_REF_NAME} )
    - kustomize build ${TMP_DIR} > manifests/progressive-delivery-demo.yaml
    - git add manifests/canary-demo.yaml
    - git commit -m "(gitlab-ci) job id ${CI_JOB_ID} - update k8s resources"
    - git push origin master